dist: xenial

language: minimal

install:
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  # Some debugging
  - fin exec --in=browser chromedriver --version
  - fin exec --in=browser java -jar /opt/selenium/selenium-server-standalone.jar --version
  - fin test
