#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
SETTINGS_PATH="${PROJECT_ROOT}/.docksal/settings"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
DRUPAL_GIT_REPO="https://git.drupalcode.org/project/drupal.git"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Clones Drupal 8 repository into docroot.
git_clone ()
{
	if [[ ! -d "$DOCROOT_PATH" ]]; then
		echo-green "Cloning Drupal 8"
		git clone "$DRUPAL_GIT_REPO" "$DOCROOT_PATH"
	fi
}

# Runs composer install in docroot
composer_install ()
{
	cd "$DOCROOT_PATH"
	echo-green "Installing dependencies..."
	composer install
}

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	echo-green "Initializing local settings..."
	copy_settings_file "${SETTINGS_PATH}/example.gitignore" "${DOCROOT_PATH}/.gitignore"
	copy_settings_file "${SETTINGS_PATH}/phpunit.xml" "${DOCROOT_PATH}/core/phpunit.xml"
	copy_settings_file "${SETTINGS_PATH}/settings.php" "${SITEDIR_PATH}/settings.php"
	copy_settings_file "${SETTINGS_PATH}/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo-green "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd "$DOCROOT_PATH"

	echo-green "Installing Drupal..."
	# We disable email sending here so site-install does not return an error
	# Credit: https://www.drupal.org/project/phpconfig/issues/1826652#comment-12071700
	drush site-install standard -y \
		install_configure_form.enable_update_status_module=NULL \
		--site-name='My Drupal 8 Site'
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
time -p git_clone
time -p composer_install
fix_permissions
init_settings
time -p site_install

echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
echo-yellow "Look for admin login credentials in the output above."

#-------------------------- END: Execution --------------------------------
